version: '3'
services:
  mongo:
    container_name: shopping_mongodb
    image: mongo:latest
    networks:
      - gateway
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  node:
    container_name: shopping_node
    restart: always
    build: .
    networks:
      - gateway
    ports:
      - 8000:4000
    volumes:
      - .:/usr/src/app
    environment:
      MONGO_URI: mongodb://mongo:27017/shopping_cart
      PORT: 4000
      TOKEN_KEY: shopping_cart_secret
      STRIPE_KEY: sk_test_51KRDFcEkE6hiXhcwbYsHyjTBtXcAwo79U1E6tSYe8pAefYk0VccqNnelxF3D37Lw5cCIZM6aN7H0kwLSqP6YGNRG00bWWxklru
      YOUR_DOMAIN: http://localhost:4000

    links:
      - mongo
    depends_on:
      - mongo

volumes:
  mongo: {}
networks:
  gateway: {}