version: 2.1 
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: echo "Hello world"
   test:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
          



