version: 2.1
jobs:
  build: 
    steps: 
      - checkout
      - run: echo "testing the microphone"
  test:
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test



